# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05b5c9a1f8240592a118fbc6fd8a862acd84db264cc6150e2d69f4709be0b735372df34bc55324a0e8e6b10698f34e2fb9ec587805ea4655d67cd8dc76fcbd5f

test:
  secret_key_base: 9237c4bc118b6d96b3c99a867b95c4684b5b45dfba075eb1622b469e4157ada73137fba6360875614d13721acc66b00afb30a3625dc70ddabe2afc93d3302b66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
